
  CREATE TABLE "SEMINAR"."ACTIVEFARMER" 
   (	"ACTID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"ACTNAME" NVARCHAR2(50), 
	"ACTTYPE" NVARCHAR2(10), 
	"ACTADDR" NVARCHAR2(100), 
	"TEL" NVARCHAR2(20), 
	"ACTDATE" DATE, 
	"ACTTIMESTA" TIMESTAMP (6), 
	"ACTTIMEEND" TIMESTAMP (6), 
	"NUMLIM" NUMBER(5,0), 
	"MEMBERNO" NVARCHAR2(100), 
	"PRICE" NUMBER(10,0), 
	"ACTDESCRI" NVARCHAR2(2000), 
	"IMGNAME" NVARCHAR2(200), 
	"ACTIMG" BLOB, 
	"ACTLOCK" NUMBER(1,0), 
	 PRIMARY KEY ("ACTID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" 
 LOB ("ACTIMG") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES ) ;

