--------------------------------------------------------
--  已建立檔案 - 星期二-十二月-01-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ACTORD
--------------------------------------------------------

  CREATE TABLE "ACTORD" 
   (	"ACTORDID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"MEMNAME" NVARCHAR2(255), 
	"MEMTEL" NVARCHAR2(255), 
	"MEMEMAIL" NVARCHAR2(20), 
	"ACTID" NUMBER(10,0), 
	"ORDACTNUM" NUMBER(3,0), 
	"TOTALPRICE" NUMBER(10,2), 
	"ORDSTATE" NUMBER(2,0), 
	"ORDTIME" TIMESTAMP (6), 
	"MEMNO" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C0014151
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C0014151" ON "ACTORD" ("ACTORDID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table ACTORD
--------------------------------------------------------

  ALTER TABLE "ACTORD" MODIFY ("ACTORDID" NOT NULL ENABLE);
  ALTER TABLE "ACTORD" ADD PRIMARY KEY ("ACTORDID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ACTORD
--------------------------------------------------------

  ALTER TABLE "ACTORD" ADD CONSTRAINT "ACTORD_FK1" FOREIGN KEY ("ACTID")
	  REFERENCES "ACTFARMER" ("ACTID") ON DELETE CASCADE ENABLE;
