CREATE TABLE MEMBER_DETAIL 
(
  MEMBER_NO NUMBER NOT NULL 
, FILENAME VARCHAR2(100 BYTE) 
, DATA BLOB 
, INTRODUCTION VARCHAR2(1000 BYTE) 
, MEMBER_NAME VARCHAR2(30 BYTE) 
, CONSTRAINT MEMBER_DETAIL_PK PRIMARY KEY 
  (
    MEMBER_NO 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX MEMBER_DETAIL_PK ON MEMBER_DETAIL (MEMBER_NO ASC) 
      LOGGING 
      TABLESPACE USERS 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE USERS 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NO INMEMORY 
NOPARALLEL 
LOB (DATA) STORE AS SYS_LOB0000082760C00003$$ 
( 
  ENABLE STORAGE IN ROW 
  CHUNK 8192 
  NOCACHE 
  LOGGING 
  TABLESPACE USERS 
  STORAGE 
  ( 
    INITIAL 106496 
    NEXT 1048576 
    MINEXTENTS 1 
    MAXEXTENTS UNLIMITED 
    BUFFER_POOL DEFAULT 
  )  
);
