 CREATE TABLE "HR"."PRODUCT" 
   (	"PRODUCTID" NUMBER(38,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"PRODUCT" VARCHAR2(50 BYTE), 
	"PRODUCTERID" NUMBER, 
	"STOCK" NUMBER(38,0), 
	"CONTENT" NUMBER(38,0), 
	"UNIT" VARCHAR2(12 BYTE), 
	"PRICE" NUMBER(12,2), 
	"DISCOUNT" NUMBER(12,2), 
	"ADDEDDATE" DATE, 
	"SHELFTIME" NUMBER(12,0), 
	"COVERIMAGE" BLOB, 
	"FILENAME" VARCHAR2(20 BYTE), 
	"DESCRIPTION" VARCHAR2(255 BYTE), 
	"CATEGORY" NUMBER(20,0), 
	 PRIMARY KEY ("PRODUCTID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "SYSAUX"  ENABLE, 
	 FOREIGN KEY ("PRODUCTERID")
	  REFERENCES "HR"."MEMBER_SIGNUP" ("MEMBER_NO") ON DELETE CASCADE ENABLE, 
	 FOREIGN KEY ("CATEGORY")
	  REFERENCES "HR"."PRODUCTCATEGORY" ("ID") ON DELETE CASCADE ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSAUX" 
 LOB ("COVERIMAGE") STORE AS SECUREFILE (
  TABLESPACE "SYSAUX" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES ) ;
