 CREATE TABLE "SEMINAR"."ACTIVE" 
   ( "ACT_ID" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
 "ACT_NAME" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
 "ACT_ADDR" VARCHAR2(255 BYTE) NOT NULL ENABLE, 
 "TEL" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
 "EXP_NUM" NUMBER(3,0) NOT NULL ENABLE, 
 "ACT_NUM" NUMBER(3,0), 
 "SIG_STAT" VARCHAR2(20 BYTE), 
 "MEMBER_NO" VARCHAR2(255 BYTE), 
 "ACT_DATE" DATE NOT NULL ENABLE, 
 "PRICE" NUMBER(10,0), 
 "ACT_TYPE" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
 "DATE_STA" DATE NOT NULL ENABLE, 
 "DATE_END" DATE NOT NULL ENABLE, 
 "ACT_DESCRI" CLOB, 
 "ACT_IMG" BLOB, 
 "ACT_VIDEO" BLOB, 
 "IMG_NAME" VARCHAR2(50 BYTE), 
 "VID_NAME" VARCHAR2(50 BYTE), 
  CONSTRAINT "ACTIVE_PK" PRIMARY KEY ("ACT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   )
   
  
CREATE SEQUENCE  "SEMINAR"."ACTIVE_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 161 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
