--------------------------------------------------------
--  已建立檔案 - 星期二-十月-13-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ORDERFORM
--------------------------------------------------------

  CREATE TABLE ORDERFORM
   (	"ORDERID" NUMBER(20,0), 
	"BUYERID" VARCHAR2(255 BYTE), 
	"BUYERNAME" VARCHAR2(255 BYTE), 
	"ADDRESS" VARCHAR2(100 BYTE), 
	"TEL" VARCHAR2(255 BYTE), 
	"BNO" VARCHAR2(20 BYTE), 
	"TOTAL" NUMBER(20,2), 
	"ORDERDATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" ;
--------------------------------------------------------
--  DDL for Index ORDERFORM_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX ORDERFORM_PK ON "HR"."ORDERFORM" ("ORDERID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" ;
--------------------------------------------------------
--  DDL for Trigger ORDERFORM_TRG1
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER ORDERFORM_TRG1 
BEFORE INSERT ON ORDERFORM 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ORDERID IS NULL THEN
      SELECT ORDERFORM_SEQ1.NEXTVAL INTO :NEW.ORDERID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "HR"."ORDERFORM_TRG1" ENABLE;
--------------------------------------------------------
--  DDL for Trigger ORDERFORM_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER ORDERFORM_TRG 
BEFORE INSERT ON ORDERFORM 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER ORDERFORM_TRG ENABLE;
--------------------------------------------------------
--  Constraints for Table ORDERFORM
--------------------------------------------------------

  ALTER TABLE ORDERFORM MODIFY ("ORDERID" NOT NULL ENABLE);
  ALTER TABLE ORDERFORM ADD CONSTRAINT "ORDERFORM_PK" PRIMARY KEY ("ORDERID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX"  ENABLE;
