--------------------------------------------------------
--  已建立檔案 - 星期二-十月-13-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ORDERDETAILS
--------------------------------------------------------

  CREATE TABLE ORDERDETAILS
   (	"ITEMID" NUMBER(20,0), 
	"ORDERID" NUMBER(20,0), 
	"PRODUCTID" NUMBER(38,0), 
	"PRODUCTERID" VARCHAR2(255 BYTE), 
	"DESCRIPTION" VARCHAR2(255 BYTE), 
	"AMOUNT" NUMBER(38,0), 
	"UNITPRICE" NUMBER(12,2), 
	"DISCOUNT" NUMBER(12,2), 
	"STATUS" NUMBER(20,0), 
	"SHIPPINGDATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" ;
--------------------------------------------------------
--  DDL for Index ORDERDETAILS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX ORDERDETAILS_PK ON ORDERDETAILS ("ITEMID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" ;
--------------------------------------------------------
--  DDL for Trigger ORDERDETAILS_TRG1
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER ORDERDETAILS_TRG1 
BEFORE INSERT ON ORDERDETAILS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ITEMID IS NULL THEN
      SELECT ORDERDETAILS_SEQ1.NEXTVAL INTO :NEW.ITEMID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER ORDERDETAILS_TRG1 ENABLE;
--------------------------------------------------------
--  DDL for Trigger ORDERDETAILS_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER ORDERDETAILS_TRG
BEFORE INSERT ON ORDERDETAILS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "HR"."ORDERDETAILS_TRG" ENABLE;
--------------------------------------------------------
--  Constraints for Table ORDERDETAILS
--------------------------------------------------------

  ALTER TABLE ORDERDETAILS MODIFY ("ITEMID" NOT NULL ENABLE);
  ALTER TABLE ORDERDETAILS ADD CONSTRAINT "ORDERDETAILS_PK" PRIMARY KEY ("ITEMID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ORDERDETAILS
--------------------------------------------------------

  ALTER TABLE ORDERDETAILS ADD CONSTRAINT "ORDERDETAILS_FK1" FOREIGN KEY ("ORDERID")
	  REFERENCES "HR"."ORDERFORM" ("ORDERID") ENABLE;
