--------------------------------------------------------
--  已建立檔案 - 星期四-十月-08-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table PRODUCTCATEGORY
--------------------------------------------------------

  CREATE TABLE PRODUCTCATEGORY 
   (	"ID" NUMBER(20,0), 
	"NAME" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" ;
--------------------------------------------------------
--  DDL for Index PRODUCTCATEGORY_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX PRODUCTCATEGORY_PK ON PRODUCTCATEGORY (ID) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" ;
--------------------------------------------------------
--  DDL for Trigger PRODUCTCATEGORY_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER PRODUCTCATEGORY_TRG 
BEFORE INSERT ON PRODUCTCATEGORY 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT PRODUCTCATEGORY_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER PRODUCTCATEGORY_TRG ENABLE;
--------------------------------------------------------
--  Constraints for Table PRODUCTCATEGORY
--------------------------------------------------------

  ALTER TABLE PRODUCTCATEGORY MODIFY (ID NOT NULL ENABLE);
  ALTER TABLE PRODUCTCATEGORY ADD CONSTRAINT PRODUCTCATEGORY_PK PRIMARY KEY (ID)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX"  ENABLE;




insert into PRODUCTCATEGORY values(1,葉菜);

insert into PRODUCTCATEGORY values(2,根莖);

insert into PRODUCTCATEGORY values(3,瓜果);

insert into PRODUCTCATEGORY values(4,茶葉);

insert into PRODUCTCATEGORY values(5,水果);
