--------------------------------------------------------
--  已建立檔案 - 星期一-十月-12-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table RECIPE
--------------------------------------------------------

  CREATE TABLE "EX"."RECIPE" 
   (	"RECIPE_ID" VARCHAR2(100 BYTE), 
	"RECIPE_DESC" VARCHAR2(500 BYTE), 
	"CATEGORY" VARCHAR2(20 BYTE), 
	"RECIPE_NAME" VARCHAR2(20 BYTE), 
	"METHOD" VARCHAR2(600 BYTE), 
	"INGREDIENTS_A" VARCHAR2(10 BYTE), 
	"INGREDIENTS_B" VARCHAR2(10 BYTE), 
	"INGREDIENTS_C" VARCHAR2(10 BYTE), 
	"INGREDIENTS_D" VARCHAR2(10 BYTE), 
	"FILENAME" VARCHAR2(30 BYTE), 
	"DATA" BLOB
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("DATA") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
