--------------------------------------------------------
--  已建立檔案 - 星期一-十月-12-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table MARKET_PRODUCT_TOTAL
--------------------------------------------------------

  CREATE TABLE "ROOT"."MARKET_PRODUCT_TOTAL" 
   (	"EMAIL" VARCHAR2(255 BYTE), 
	"MARKET_NAME" VARCHAR2(50 BYTE), 
	"PRODUCT_ID" VARCHAR2(255 BYTE), 
	"PRODUCT_NAME" VARCHAR2(50 BYTE), 
	"PRODUCT_AREA" VARCHAR2(50 BYTE), 
	"PRODUCT_CATEGORY" VARCHAR2(50 BYTE), 
	"QUANTITY" NUMBER(10,0), 
	"PRICE" NUMBER(10,0), 
	"REPORT" NUMBER(10,0), 
	"UNIT" VARCHAR2(20 BYTE), 
	"DISCOUNT" NUMBER(10,2)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index MARKET_PRODUCT_TOTAL_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ROOT"."MARKET_PRODUCT_TOTAL_PK" ON "ROOT"."MARKET_PRODUCT_TOTAL" ("PRODUCT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table MARKET_PRODUCT_TOTAL
--------------------------------------------------------

  ALTER TABLE "ROOT"."MARKET_PRODUCT_TOTAL" MODIFY ("PRODUCT_ID" NOT NULL ENABLE);
  ALTER TABLE "ROOT"."MARKET_PRODUCT_TOTAL" ADD CONSTRAINT "MARKET_PRODUCT_TOTAL_PK" PRIMARY KEY ("PRODUCT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
