--------------------------------------------------------
--  已建立檔案 - 星期一-十月-12-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table MARKET_SELLER_ID
--------------------------------------------------------

  CREATE TABLE "ROOT"."MARKET_SELLER_ID" 
   (	"PRODUCT_IMG" BLOB, 
	"DESCRIPTION" VARCHAR2(225 BYTE), 
	"PRODUCT_ID" VARCHAR2(225 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("PRODUCT_IMG") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  Ref Constraints for Table MARKET_SELLER_ID
--------------------------------------------------------

  ALTER TABLE "ROOT"."MARKET_SELLER_ID" ADD CONSTRAINT "MARKET_SELLER_ID_FK1" FOREIGN KEY ("PRODUCT_ID")
	  REFERENCES "ROOT"."MARKET_PRODUCT_TOTAL" ("PRODUCT_ID") ENABLE;
